#!/bin/bash

application_name=$1
window_name=$2

# TODO switch to go instead of bringing


[[ -z "$application_name" ]] && echo "application name argument needed" && exit 1
[[ -z "$window_name" ]] && echo "window name argument needed" && exit 1


current_windows=$(xdotool search --class "$window_name" | xargs -I sw xdotool getwindowname sw | sort -u)

if [ -z "$current_windows" ]; then
	$application_name &
	exit
fi

active_window=$(xdotool getwindowfocus getwindowname)
for name_part in ${active_window[@]}
do
# 	echo $name_part
 	if [ "$name_part" = "$window_name" ]; then	
		xdotool key super+Down
		exit
		# TODO put the window back to its og position
	fi
done
echo $active_window
echo $window_name

# will not work at all with multiple windows
window_location=$(wmctrl -l | grep -i "$window_name" | awk '{print $1}' | head -1)
wmctrl -i -r $window_location -t -1	
xdotool search --class "$window_name" | xargs -I sw xdotool windowactivate sw
